### ISSUE TITLE
我用了你的pixiv_host不能访问P站。

### ISSUE THREAD

**Issue by embeddedsecurity** [lovelyyoshino/pixiv_host#1]
### CHROME浏览器 WIN7X64。DNS180.76.76.76
<img width="960" alt="chrome_2018-07-24_18-16-52" src="https://user-images.githubusercontent.com/24518756/43132346-14093728-8f6e-11e8-9ae5-7f54cb9f1d71.png">
<img width="941" alt="chrome_2018-07-24_18-28-54" src="https://user-images.githubusercontent.com/24518756/43132793-75249222-8f6f-11e8-8dc0-587413752d9a.png">

**Comment by lovelyyoshino** [comment]
你好，已经更新

**Comment by lovelyyoshino** [comment]
原本的Host已经失效
