### ISSUE TITLE
使用pixiv_host不能访问P站，解决方法

### ISSUE THREAD

**Issue by embeddedsecurity** [lovelyyoshino/pixiv_host#2]
我用了电信运营商分配的DNS和百度的DNS均无法打开
![1111](https://user-images.githubusercontent.com/24518756/44829413-539d1f00-ac4f-11e8-9f79-954695abb475.jpg)
请更新HOSTS
就算用了“P站hosts修改.bat"也无法访问P站。
我是WIN8.1系统，用“P站hosts修改.bat"也无法修改HOSTS内容，我就从C:\Windows\System32\drivers\etc路径里把HOSTS复制到桌面上手动修改，再把修改完成的HOSTS复制回C:\Windows\System32\drivers\etc就可以访问P站了，修改效果如下
![1111](https://user-images.githubusercontent.com/24518756/44830431-37e84780-ac54-11e8-9b9d-b4275b428d2d.jpg)
![2222](https://user-images.githubusercontent.com/24518756/44830432-39197480-ac54-11e8-965b-d058c80d1df2.jpg)
![2222](https://user-images.githubusercontent.com/24518756/44830943-f907c100-ac56-11e8-9620-c5cc4b3ded0f.jpg)
![Honeycam 2020-09-21 06-08-21](https://user-images.githubusercontent.com/24518756/93921016-8fc5df80-fd42-11ea-8615-786829b940e5.gif)

感谢楼主提供HOSTS文件造福众生。同时也给其他网友提供使用HOSTS使用经验

**Comment by lovelyyoshino** [comment]
你好，是否可以将最新的Host文件传输过来，我进行修改，或者你提交修改Host文件

**Comment by embeddedsecurity** [comment]
@lovelyyoshino 感谢你的帮助。现在你的P站HOSTS可以正常，也要发过来吗？

**Comment by lovelyyoshino** [comment]
昨天好像HOST不起作用了，还有就是我怀疑gihub上bat文件无法使用的原因应该是字体格式问题，我重新传输仍然出现该问题

**Comment by lovelyyoshino** [comment]
而且对于TXT文件的上传，进测试下载后txt文件分布为一整行，而未出现bat文件分段，从而导致运行错误，暂时未想到较好的方法解决
